# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

# | Vagrant
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


    # | global

        # base - box
        config.vm.box = "ubuntu/trusty64"

        # network - adapter - bridged
        config.vm.network "public_network"

        # provision - shell - bash
        config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
        config.vm.provision "shell", path: "../bin/getup"

        # ssh - agent - fowarding
        config.ssh.forward_agent = true

        # | VirtualBox
        config.vm.provider "virtualbox" do |vb|

            # VBoxManage - settings
            vb.customize [
                "modifyvm", :id,
                "--memory", "2048",
            ]

        end
        # VirtualBox |

    # global |


    # | machine(s)

        # | magento2
        config.vm.define "magento2" do |web|
            config.vm.hostname = "magento2"
            config.vm.provider :virtualbox do |vb|
                vb.name = "magento2"
                vb.cpus = 4
            end
        end
        # magento2 |

    # machine(s) |


end
# Vagrant |
